server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Reverse proxy vers le User Service
    location /api/auth {
        proxy_pass http://user-service:8080;
        proxy_set_header Host $host;
    }
    
    location /api/users {
        proxy_pass http://user-service:8080;
        proxy_set_header Host $host;
    }

    # Reverse proxy vers le Movie Service
    location /api/movies {
        proxy_pass http://movie-service:8080;
        proxy_set_header Host $host;
    }

    # Reverse proxy vers le Rating Service
    location /api/ratings {
        proxy_pass http://rating-service:8080;
        proxy_set_header Host $host;
    }

    # Reverse proxy vers le Recommendation Service
    location /api/recommendations {
        proxy_pass http://recommendation-service:8080;
        proxy_set_header Host $host;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
