server {
    listen 80;
    server_name localhost;
    # Redirection automatique vers HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    # Optimisation SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Reverse proxy vers le User Service
    location /api/auth {
        proxy_pass http://user-service:8080;
        proxy_set_header Host $host;
    }
    
    location /api/users {
        proxy_pass http://user-service:8080;
        proxy_set_header Host $host;
    }

    # Reverse proxy vers le Movie Service
    location /api/movies {
        proxy_pass http://movie-service:8080;
        proxy_set_header Host $host;
    }

    # Reverse proxy vers le Rating Service
    location /api/ratings {
        proxy_pass http://rating-service:8080;
        proxy_set_header Host $host;
    }

    # Reverse proxy vers le Recommendation Service
    location /api/recommendations {
        proxy_pass http://recommendation-service:8080;
        proxy_set_header Host $host;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
